### ISSUE TITLE
Astro Endpoints are not working

### ISSUE THREAD

**Issue by MykalMachon** [denoland/deno-astro-adapter#25]
Hello all! 

I've recently tried moving [my blog](https://github.com/mykalmachon/mykal.codes) over to the deno runtime via this adapter.
_Almost_ everything is working okay. The exception being all of my sites [Astro "endpoints".](https://docs.astro.build/en/guides/endpoints/). 

I use these to generate RSS (XML) and JSON feed files for my blog post content.

## What goes wrong
When running the site under deno, I see a 500 error and receive the following stack trace in the console:

 ```bash
22:17:23 [ERROR] TypeError: Cannot change headers: headers are immutable
    at Headers.set (ext:deno_fetch/20_headers.js:425:13)
    at setOriginHeader (file:///home/mykal/projects/mykalmachon/mykal.codes/website/dist/server/entry.mjs:91871:19)
    at Function.create (file:///home/mykal/projects/mykalmachon/mykal.codes/website/dist/server/entry.mjs:91957:5)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async _App.render (file:///home/mykal/projects/mykalmachon/mykal.codes/website/dist/server/entry.mjs:92711:29)
    at async Server.handler (file:///home/mykal/projects/mykalmachon/mykal.codes/website/dist/server/entry.mjs:92895:24)
    at async Server.#respond (https://deno.land/std@0.177.0/http/server.ts:299:18)
```

## Dependencies 
Here are my dependencies 

```json
{
  "name": "website",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "deno run -A ./dist/server/entry.mjs",
    "format": "deno fmt && prettier --write .",
    "info": "astro info"
  },
  "dependencies": {
    "@astrojs/node": "^8.3.4",
    "@deno/astro-adapter": "^0.1.3",
    "@uidotdev/usehooks": "^2.3.1",
    "astro": "^4.16.1",
    "astro-icon": "^0.8.1",
    "markdown-it": "^13.0.2",
    "minisearch": "^6.3.0",
    "open-props": "^1.5.15",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-snowfall": "^1.2.1"
  },
  "devDependencies": {
    "@astrojs/react": "^3.6.2",
    "@astrojs/rss": "^4.0.8",
    "@astrojs/sitemap": "^3.2.0",
    "@types/markdown-it": "^13.0.1",
    "@types/react": "^18.2.22",
    "@types/react-dom": "^18.2.7",
    "reading-time": "^1.5.0",
    "sanitize-html": "^2.11.0"
  }
}
```

**Comment by Phenome** [comment]
I have the same issue since I redeployed my astro site with SSR, with the backend now on Deno 2, I think

**Comment by marc2332** [comment]
I think this can be closed, it works just fine with the latest release :)

**Comment by MykalMachon** [comment]
I did some testing and I've confirmed that this doesn't throw errors anymore.
Thank you for the heads up @marc2332
