### ISSUE TITLE
[ERR_MODULE_NOT_FOUND] Cannot find module ... zod-to-json-schema ...

### ISSUE THREAD

**Issue by endigma** [denoland/deno-astro-adapter#30]
Following the instructions [here](https://docs.deno.com/runtime/fundamentals/web_dev/#astro) trying to get Astro working with Deno 2, the `deno install` command functions correctly but `deno task build` fails due to the error in the title. 

```
[ERR_MODULE_NOT_FOUND] Cannot find module 'file:///project//node_modules/.deno/zod-to-json-schema@3.23.4/node_modules/zod-to-json-schema/dist/esm/parsers/branded' imported from 'file:///project//node_modules/.deno/zod-to-json-schema@3.23.4/node_modules/zod-to-json-schema/dist/esm/parsers/record.js'
  Stack trace:
    at async runCommand (file:///project//node_modules/.deno/astro@4.16.7/node_modules/astro/dist/cli/index.js:137:23)
 ```

This is interesting as https://deno.com/blog/v2.0 says:
> Finally, you can use Deno 2 with your favorite JavaScript framework. Deno 2 supports Next.js, --> **Astro** <--, Remix, Angular, SvelteKit, QwikCity and many other frameworks.

**Comment by michaelpayne02** [comment]
I have a similar problem using deck.gl and one of its dependencies luma.gl. It looks like relative paths aren't being resolved correctly in certain import statements. 

```
00:21:08 [ERROR] [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/michael/Documents/portfolio/node_modules/.deno/@luma.gl+shadertools@9.0.27/node_modules/@luma.gl/shadertools/dist/modules/lib/glsl-utils/highlight.js' imported from 'file:///Users/michael/Documents/portfolio/node_modules/.deno/@luma.gl+shadertools@9.0.27/node_modules/@luma.gl/shadertools/dist/modules//math/random/random.js'
  Stack trace:
    at async SSRCompatModuleRunner.directRequest (/Users/michael/Documents/portfolio/node_modules/.deno/vite@6.0.5/node_modules/vite/dist/node/module-runner.js:1228:24)
    at undefined
    at async SSRCompatModuleRunner.directRequest (/Users/michael/Documents/portfolio/node_modules/.deno/vite@6.0.5/node_modules/vite/dist/node/module-runner.js:1279:61)
    at async SSRCompatModuleRunner.cachedRequest (/Users/michael/Documents/portfolio/node_modules/.deno/vite@6.0.5/node_modules/vite/dist/node/module-runner.js:1174:76)
```

relevant file:
```js
// luma.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors
import { glsl } from "../../../lib/glsl-utils/highlight.js";
const fs = `\
float random(vec3 scale, float seed) {
return fract(sin(dot(gl_FragCoord.xyz + seed, scale)) * 43758.5453 + seed);
}
`;
/** Quick random generator for fragment shaders */
export const random = {
    name: 'random',
    fs
};
```

Notice, the relative import shown above should resolve to `file:///Users/michael/Documents/portfolio/node_modules/.deno/@luma.gl+shadertools@9.0.27/node_modules/@luma.gl/shadertools/dist/lib/glsl-utils/highlight.js` 
but instead it resolves to `file:///Users/michael/Documents/portfolio/node_modules/.deno/@luma.gl+shadertools@9.0.27/node_modules/@luma.gl/shadertools/dist/modules/lib/glsl-utils/highlight.js`
The `modules` folder is still there. It should have gone up three folders, but instead it only went up two for some reason.
